---
commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  version: 0.7.6
  version_files:
  - Cargo.toml:^version
  - helm/Chart.yaml:version
  version_provider: commitizen
  version_scheme: semver
  major_version_zero: true
  update_changelog_on_bump: true
  changelog_file: CHANGELOG.md

