{{- if not .Values.management.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  config.yaml: |
    providers:
      {{- range .Values.config.providers }}
      - {{ toYaml . | nindent 8 | trim }}
      {{- end }}
    models:
      {{- range .Values.config.models }}
      - key: {{ .key }}
        type: {{ .type }}
        provider: {{ .provider }}
        {{- if .deployment }}
        deployment: "{{ .deployment }}"
        {{- end }}
      {{- end }}
    
    pipelines:
      {{- range .Values.config.pipelines }}
      - name: {{ .name }}
        type: {{ .type }}
        plugins:
        {{- range .plugins }}
          - {{ toYaml . | nindent 12 | trim }}
        {{- end }}
      {{- end }}
{{- end }}
